name: Check

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ""
          key: ""
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo +nightly fmt --check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y protobuf-compiler
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.65.0
          components: clippy
      - uses: actions/setup-node@v3
        with:
          node-version: 19.0.1
      - run: npm i --ci
      - run: cargo clippy

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y protobuf-compiler
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ""
          key: ""
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.65.0
      - uses: actions/setup-node@v3
        with:
          node-version: 19.0.1
      - uses: taiki-e/install-action@nextest
      - run: npm i --ci
      - run: cargo build
      - run: cargo nextest run

  acceptance-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y protobuf-compiler
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ""
          key: ""
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.65.0
      - uses: actions/setup-node@v3
        with:
          node-version: 19.0.1
      - run: npm i --ci
      - run: npx playwright install --with-deps
      - run: cargo build
      - uses: isbang/compose-action@v1.4.0
        with:
          compose-file: ./docker-compose.deps.yml
      - run: bash -c "until docker exec postgres pg_isready; do sleep 5; done"
      - run: npm run acceptance-tests
